use pulp 3.6 for katello 3.17
theforeman/forklift pull request #1210
Opened 2020-09-16 13:00 UTC by jlsherrill

2020-09-16 13:00 UTC, jlsherrill commented
note, we may want to wait for rc2 to merge this

2020-11-12 08:23 UTC, evgeni commented
@jlsherrill is this still needed? I'd assume so.

We have a test that for 3.17 we don't set a pulpcore version:
https://github.com/theforeman/forklift/blob/d55e8ce27144196e365bb7b99067d9c72315a823/roles/forklift_versions/molecule/default/verify.yml#L11-L25

This will need to be adjusted (probably just flipping it to Foreman 2.1/Katello 3.16 is the simplest here)

2020-11-18 14:18 UTC, ekohl requested changes

2020-11-18 14:18 UTC, ekohl commented on vagrant/config/versions.yaml
> +    pulpcore: '3.6'
By now this should be 3.7, right?

2020-11-18 15:02 UTC, evgeni commented
#1222 should fix that all :)

2020-11-19 08:22 UTC, evgeni commented
closing given #1222 is merged.

2020-11-19 08:22 UTC, closed without merging