Enable Ruby 2.7 for nightly and Foreman 2.5+ before installing installer
theforeman/forklift pull request #1332
Opened 2021-04-06 20:25 UTC by ehelms

2021-04-06 20:40 UTC, evgeni requested changes

2021-04-06 20:40 UTC, evgeni commented on roles/foreman_installer/tasks/packages.yml
> +    - foreman_repositories_version == "nightly" or 2.5 is version(foreman_repositories_version, '>')
This tests if 2.5 > f_r_v, which is not what you want ;)
`foreman_repositories_version is version ('2.5', '>=')` is probably more what's wanted here?

2021-04-06 20:42 UTC, evgeni commented
Won't this break updates as those already have `ruby:2.5` enabled?

2021-04-06 22:20 UTC, ehelms commented
> Won't this break updates as those already have `ruby:2.5` enabled?

My testing of upgrades passed locally. That is because as far as I can tell, the way we are using the dnf Ansible module it performs a reset on the ruby module and then an enable on the 2.7 Ruby profile.

2021-04-07 07:47 UTC, evgeni approved these changes

2021-04-07 11:41 UTC, merged