Updates katello 4.1 to user pulpcore 3.14
theforeman/forklift pull request #1379
Opened 2021-07-08 18:41 UTC by jjeffers

2021-07-09 10:32 UTC, ekohl requested changes
Could you fix the merge conflict and fix the typo in the commit message?

2021-07-12 12:40 UTC, ekohl requested changes

2021-07-12 12:40 UTC, ekohl commented on vagrant/config/versions.yaml
> +    pulp: '2.21'
This looks like a bad rebase that ends up reverting ab476516d1cf9809d9bc02c6456bdbebbf40c2df
```suggestion
```

2021-07-12 14:01 UTC, ekohl approved these changes
Code wise :+1: but this is just one piece of the puzzle. Last time we merged forklift too soon and broke many things. Let's wait until the packaging and core PRs are also ready. I also think we need to prepare an installer cherry pick PR.

2021-07-12 14:05 UTC, jjeffers commented
> Code wise  but this is just one piece of the puzzle. Last time we merged forklift too soon and broke many things. Let's wait until the packaging and core PRs are also ready. I also think we need to prepare an installer cherry pick PR.

Ok understood.

2021-07-14 07:13 UTC, evgeni commented
Everything else is ready, so let's do it!

2021-07-14 07:13 UTC, merged