Add box defitinition for foreman 3.2
theforeman/forklift pull request #1468
Opened 2022-02-07 21:05 UTC by zjhuntin

2022-02-08 12:53 UTC, ekohl requested changes
Please always copy from nightly, never from a stable release. There are boxes missing now.

2022-02-08 13:25 UTC, zjhuntin commented
@ekohl okay, redone based on nightly.

2022-02-08 14:05 UTC, ekohl approved these changes
Looks correct. Shouldn't be merged until we actually branch and want to test RC1, otherwise nightly upgrade pipelines break.

2022-02-08 18:24 UTC, zjhuntin commented on vagrant/config/versions.yaml
> +      - 'centos8'
Updated and removed centos8 :)

2022-02-14 16:22 UTC, ekohl approved these changes

2022-02-14 16:22 UTC, merged