Fix stagingyum repositories URLs
theforeman/forklift pull request #1765
Opened 2024-02-12 18:30 UTC by wbclark

https://stagingyum.theforeman.org/foreman/staging/el8/x86_64/ returns 404, it should be https://stagingyum.theforeman.org/foreman/nightly/el8/x86_64/

This fixes the issue for those who don't have in their box yaml: katello_repositories_version: nightly

2024-02-12 18:36 UTC, evgeni requested changes
No, you gotta set the right version. "Staging" is not a version.

2024-02-12 18:42 UTC, wbclark commented
> No, you gotta set the right version. "Staging" is not a version.

it's not clear to me where that's coming from.

I had `katello_repositories_version: nightly` in my box yaml already so it just worked for me.

But that's already the default for the katello_repositories role: https://github.com/theforeman/forklift/blob/master/roles/katello_repositories/defaults/main.yml#L2

2024-02-12 19:33 UTC, ianballou commented
> CC: @ianballou this looks like it should have been working for you already using the defaults -- were you passing some extra variables to your box that were breaking it?

Very likely yes! However I got it to work with:

```
centos8-katello-devel-2:
  primary: true
  box: centos8-stream
  cpus: 2
  memory: 15000
  ansible:
    playbook: 'playbooks/katello_devel.yml'
    group: 'devel'
    variables:
      ssh_forward_agent: true
      foreman_installer_options:
        - "--foreman-proxy-content-enable-ostree=true"
      foreman_repositories_environment: staging
      katello_repositories_environment: staging
      foreman_repositories_version: nightly
      katello_repositories_version: nightly
```

2024-02-12 19:39 UTC, evgeni commented
Every release pipeline uses those repos to validate them before pushing them live ;)

2024-02-23 19:18 UTC, wbclark commented
Closing as this was not ultimately needed.

2024-02-23 19:18 UTC, closed without merging